### PR TITLE
Add configurable feed length

### PR DESCRIPTION
**Pull request by MunifTanjim**
Reason for `REACT_APP_` prefix: https://create-react-app.dev/docs/adding-custom-environment-variables#adding-development-environment-variables-in-env

### CODE REVIEW

**Comment by mugli** [comment]
Hey, thanks again. You'll get faster response if you request review explicitly from the right panel after creating a PR :)

**Comment by mugli** [comment]
Do you think env vars are the right place to configure feed-length? How about localstorage? I understand we don't have a UI right now to configure anything. But if we had, probably feed-length would suit there more than env variables (which requires restarting the app after you change values)?

**Comment by MunifTanjim** [comment]
> Do you think env vars are the right place to configure feed-length?

**Comment by MunifTanjim** [comment]
> Do you think env vars are the right place to configure feed-length?

Nope, it's just a quick fix ( I was looking at the Orkid UI and wished the feed displayed more than 10 entries )

> How about localstorage?

Didn't think about that. That would be more appropriate.

**Comment by mugli** [comment]
Feel free to make the big change 🙃

**Pull request closed without merging**
